version: "3.7"

services:
  node:
    image: continuumio/anaconda3:2020.11
    command: jupyter lab --port=8888 --no-browser --ip=0.0.0.0 --allow-root
    volumes: 
      - ./data:/data
    ports:
      - 8888:8888